name: 'Run E2E Tests'
description: 'Execute end-to-end tests against running Waterfall application'

inputs:
  test_scope:
    description: 'Scope of tests to run (build|publish|full)'
    required: false
    default: 'build'
  web_url:
    description: 'URL of the running application'
    required: false
    default: 'https://localhost'
  timeout:
    description: 'Timeout for tests in seconds'
    required: false
    default: '300'

runs:
  using: 'composite'
  steps:
    - name: Clone E2E Test Repository
      shell: bash
      run: |
        echo "🧪 Cloning E2E test repository..."
        git clone https://github.com/bengeek06/e2e-waterfall.git e2e-tests
        cd e2e-tests
        echo "✅ E2E repository cloned"

    - name: Setup Python Environment
      shell: bash
      run: |
        cd e2e-tests
        echo "🐍 Setting up Python environment..."
        python -m venv venv
        source venv/bin/activate
        pip install --no-cache-dir -r requirements.txt
        echo "✅ Python environment ready"

    - name: Install Chrome for Selenium
      shell: bash
      run: |
        echo "🌐 Installing Chrome for Selenium tests..."
        sudo apt-get update -qq
        sudo apt-get install -y chromium-browser
        chromium --version
        echo "✅ Chrome installed"

    - name: Configure test environment
      shell: bash
      run: |
        echo "⚙️ Configuring test environment..."
        
        # Create .env.test file with proper configuration in e2e-tests directory
        cd e2e-tests
        cat > .env.test << EOF
        WEB_URL=https://localhost
        COMPANY_NAME=E2ETestCompany
        LOGIN=e2e@test.com
        PASSWORD=E2ETestPassword123!
        LOG_LEVEL=INFO
        EOF
        
        # Also export as environment variables for GitHub Actions
        echo "WEB_URL=https://localhost" >> $GITHUB_ENV
        echo "COMPANY_NAME=E2ETestCompany" >> $GITHUB_ENV
        echo "LOGIN=e2e@test.com" >> $GITHUB_ENV
        echo "PASSWORD=E2ETestPassword123!" >> $GITHUB_ENV
        echo "LOG_LEVEL=INFO" >> $GITHUB_ENV
        
        echo "📁 Environment file created at: $(pwd)/.env.test"
        echo "📋 Content:"
        cat .env.test
        
        echo "✅ Environment configured with:"
        echo "  - URL: https://localhost"
        echo "  - Company: E2ETestCompany" 
        echo "  - Login: e2e@test.com"
        echo "  - Log Level: INFO"

    - name: Wait for application initialization
      shell: bash
      run: |
        echo "⏳ Waiting for application to be ready..."
        
        # Wait for health endpoint to be available
        timeout 120s bash -c 'until curl -k -f https://localhost/health; do echo "Waiting for health endpoint..."; sleep 5; done'
        
        echo "✅ Application health endpoint is ready"
        
        # Wait a bit more for full initialization
        echo "⏳ Waiting for application initialization (30s)..."
        sleep 30
        echo "✅ Application should be fully ready"

    - name: Initialize application if needed
      shell: bash
      run: |
        cd e2e-tests
        source venv/bin/activate
        
        echo "🚀 Checking if application needs initialization..."
        
        # Debug environment variables
        echo "🔍 Debug: Environment variables loaded:"
        echo "  WEB_URL=$WEB_URL"
        echo "  COMPANY_NAME=$COMPANY_NAME" 
        echo "  LOGIN=$LOGIN"
        echo "  LOG_LEVEL=$LOG_LEVEL"
        
        # Run a quick initialization check and auto-initialize if needed
        python -c "
        import requests
        import json
        import sys
        
        try:
            # Check if app is already initialized
            response = requests.get('https://localhost/api/identity/init-db', verify=False, timeout=10)
            if response.status_code == 200:
                data = response.json()
                if data.get('initialized', False):
                    print('✅ Application already initialized')
                    sys.exit(0)
            
            print('🔧 Application needs initialization...')
            
            # Initialize Identity service
            identity_payload = {
                'company': {'name': 'E2ETestCompany'},
                'user': {'email': 'e2e@test.com', 'password': 'E2ETestPassword123!'}
            }
            
            print('📡 Initializing Identity service...')
            response = requests.post(
                'https://localhost/api/identity/init-db',
                json=identity_payload,
                headers={'Content-Type': 'application/json'},
                verify=False,
                timeout=30
            )
            
            if response.status_code != 201:
                print(f'❌ Identity initialization failed: {response.status_code} - {response.text}')
                sys.exit(1)
                
            identity_data = response.json()
            company_id = identity_data.get('company', {}).get('id')
            
            print(f'✅ Identity initialized - Company ID: {company_id}')
            
            # Initialize Guardian service  
            guardian_payload = {
                'company': {'name': 'E2ETestCompany', 'company_id': company_id},
                'user': {'email': 'e2e@test.com', 'user_id': identity_data.get('user', {}).get('id')}
            }
            
            print('🛡️ Initializing Guardian service...')
            response = requests.post(
                'https://localhost/api/guardian/init-db',
                json=guardian_payload,
                headers={'Content-Type': 'application/json'},
                verify=False,
                timeout=30
            )
            
            if response.status_code != 201:
                print(f'❌ Guardian initialization failed: {response.status_code} - {response.text}')
                sys.exit(1)
                
            print('✅ Guardian initialized successfully')
            print('🎉 Application fully initialized and ready for E2E tests!')
            
        except Exception as e:
            print(f'❌ Initialization error: {e}')
            sys.exit(1)
        "

    - name: Run E2E Tests
      shell: bash
      run: |
        cd e2e-tests
        source venv/bin/activate
        
        echo "🧪 Running E2E tests (scope: ${{ inputs.test_scope }})..."
        
        if [ "${{ inputs.test_scope }}" = "build" ]; then
          # Tests rapides pour validation de build
          echo "Running build validation tests..."
          timeout ${{ inputs.timeout }} pytest api/auth/ api/*/test_*system.py -v --tb=short --maxfail=3
        elif [ "${{ inputs.test_scope }}" = "publish" ]; then
          # Tests complets pour validation de publication
          echo "Running comprehensive tests for published image..."
          timeout ${{ inputs.timeout }} pytest api/ ui/test_app_init.py ui/login/test_login.py -v --tb=short --maxfail=5
        else
          # Tests complets
          echo "Running full test suite..."
          timeout ${{ inputs.timeout }} pytest api/ ui/ -v --tb=short --maxfail=5
        fi
        
        echo "✅ E2E tests completed successfully!"

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: e2e-test-results-${{ inputs.test_scope }}
        path: |
          e2e-tests/logs/
          e2e-tests/screenshots/
        retention-days: 7