name: 'Run E2E Tests'
description: 'Execute end-to-end tests against running Waterfall application'

inputs:
  test_scope:
    description: 'Scope of tests to run (build|publish|full)'
    required: false
    default: 'build'
  web_url:
    description: 'URL of the running application'
    required: false
    default: 'https://localhost'
  timeout:
    description: 'Timeout for tests in seconds'
    required: false
    default: '300'

runs:
  using: 'composite'
  steps:
    - name: Clone E2E Test Repository
      shell: bash
      run: |
        echo "🧪 Cloning E2E test repository..."
        git clone https://github.com/bengeek06/e2e-waterfall.git e2e-waterfall
        cd e2e-waterfall
        echo "✅ E2E repository cloned"

    - name: Setup Python environment
      shell: bash
      run: |
        cd e2e-waterfall
        echo "🐍 Setting up Python environment..."
        python -m venv venv
        source venv/bin/activate
        pip install --no-cache-dir -r requirements.txt
        echo "✅ Python environment ready"

    - name: Install Chrome for Selenium
      shell: bash
      run: |
        echo "🌐 Installing Chrome for Selenium tests..."
        sudo apt-get update -qq
        sudo apt-get install -y chromium-browser
        chromium --version
        echo "✅ Chrome installed"

    - name: Configure test environment
      shell: bash
      run: |
        echo "⚙️ Configuring test environment..."
        
        # Create .env.test file with proper configuration in e2e-waterfall directory
        cd e2e-waterfall
        cat > .env.test << EOF
        WEB_URL=https://localhost
        COMPANY_NAME=E2ETestCompany
        LOGIN=e2e@test.com
        PASSWORD=E2ETestPassword123!
        LOG_LEVEL=INFO
        EOF
        
        # Export as environment variables for immediate use
        export WEB_URL=https://localhost
        export COMPANY_NAME=E2ETestCompany
        export LOGIN=e2e@test.com
        export PASSWORD=E2ETestPassword123!
        export LOG_LEVEL=INFO
        
        # Also add to GitHub Actions environment for persistence
        echo "WEB_URL=https://localhost" >> $GITHUB_ENV
        echo "COMPANY_NAME=E2ETestCompany" >> $GITHUB_ENV
        echo "LOGIN=e2e@test.com" >> $GITHUB_ENV
        echo "PASSWORD=E2ETestPassword123!" >> $GITHUB_ENV
        echo "LOG_LEVEL=INFO" >> $GITHUB_ENV
        
        echo "📁 Environment file created at: $(pwd)/.env.test"
        echo "📋 Content:"
        cat .env.test
        
        echo "✅ Environment configured with:"
        echo "  - URL: https://localhost"
        echo "  - Company: E2ETestCompany" 
        echo "  - Login: e2e@test.com"
        echo "  - Log Level: INFO"

    - name: Wait for application initialization
      shell: bash
      run: |
        echo "⏳ Waiting for application to be ready..."
        
        # Wait for health endpoint to be available
        timeout 120s bash -c 'until curl -k -f https://localhost/health; do echo "Waiting for health endpoint..."; sleep 5; done'
        
        echo "✅ Application health endpoint is ready"
        
        # Wait a bit more for full initialization
        echo "⏳ Waiting for application initialization (30s)..."
        sleep 30
        echo "✅ Application should be fully ready"

    - name: Debug environment
      shell: bash
      run: |
        echo "🔍 Debug: Environment variables:"
        echo "  WEB_URL=$WEB_URL"
        echo "  COMPANY_NAME=$COMPANY_NAME" 
        echo "  LOGIN=$LOGIN"
        echo "  LOG_LEVEL=$LOG_LEVEL"
        
        cd e2e-waterfall
        echo "🔍 Debug: .env.test file content:"
        cat .env.test
        
        echo "🔍 Debug: Testing Python environment loading:"
        source venv/bin/activate
        python -c "
        import os
        import requests
        from dotenv import load_dotenv
        load_dotenv('.env.test')
        web_url = os.getenv('WEB_URL', 'https://localhost')
        login = os.getenv('LOGIN', 'e2e@test.com')
        password = os.getenv('PASSWORD', 'E2ETestPassword123!')
        print(f'Python WEB_URL: {web_url}')
        print(f'Python LOGIN: {login}')
        print(f'Python PASSWORD: {password}')
        
        # Test if app is initialized
        try:
            response = requests.get(f'{web_url}/api/identity/init-db', verify=False, timeout=5)
            if response.status_code == 200:
                data = response.json()
                print(f'App initialized: {data.get(\"initialized\", False)}')
            else:
                print(f'Init check failed: {response.status_code}')
                
            # Test login with these credentials
            login_response = requests.post(
                f'{web_url}/api/auth/login',
                json={'email': login, 'password': password},
                headers={'Content-Type': 'application/json'},
                verify=False,
                timeout=10
            )
            print(f'Login test result: {login_response.status_code}')
            if login_response.status_code != 200:
                print(f'Login error: {login_response.text}')
        except Exception as e:
            print(f'Debug test error: {e}')
        "

    - name: Run E2E Tests
      shell: bash
      run: |
        cd e2e-waterfall
        source venv/bin/activate
        
        echo "🧪 Running E2E tests (scope: ${{ inputs.test_scope }})..."
        
        # Simple pytest execution like in the working script
        if [ "${{ inputs.test_scope }}" = "build" ]; then
          echo "Running build validation tests..."
          python -m pytest api/auth/ api/*/test_*system.py -v --tb=short --maxfail=3
        elif [ "${{ inputs.test_scope }}" = "publish" ]; then
          echo "Running comprehensive tests..."  
          python -m pytest api/ ui/login/ -v --tb=short --maxfail=5
        else
          echo "Running full test suite..."
          python -m pytest api/ ui/ -v --tb=short --maxfail=5
        fi

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: e2e-test-results-${{ inputs.test_scope }}
        path: |
          e2e-waterfall/logs/
          e2e-waterfall/screenshots/
        retention-days: 7